FROM hlsiira/atheos

# Install Python (default, which may be Python 2.x), Python 3, pip for both Python versions, and build-essential
RUN apt update && \
    apt install -y \
        python \
        python3 \
        python-pip \
        python3-pip \
        build-essential && \

# Or, using python3-pip (for Python 3.x)
# RUN python3 -m pip install numpy pandas
